import MobileModule from "./module/MobileModule.js";
import AosModule from "./module/AosModule.js";
import WowModule from "./module/WowModule.js";
import BtnToTopModule from "./module/BtnToTopModule.js";
import PopupModule from "./module/PopupModule.js";
import SwiperModule from "./module/SwiperModule.js";
import CountUpModule from "./module/CountUpModule.js";
import LoadModule from "./module/LoadModule.js";
import SelectCusModule from "./module/SelectCusModule.js";
import CheckModule from "./module/CheckModule.js";
import SearchModule from "./module/SearchModule.js";
import Select2Module from "./module/Select2Module.js";
import LetterModule from "./module/LetterModule.js";
import GalleryModule from "./module/GalleryModule.js";
import TabModule from "./module/TabModule.js";
import IsotopeModule from "./module/IsotopeModule.js";
import HeaderModule from "./module/HeaderModule.js";
import PlusMinusModule from "./module/PlusMinusModule.js";
import SideModule from "./module/SideModule.js";
import ShowHideModule from "./module/ShowHideModule.js";
import FaqsModule from "./module/FaqsModule.js";
import MapLoadModule from "./module/MapLoadModule.js";

window.addEventListener("DOMContentLoaded", () => {
    MobileModule();
    AosModule();
    // WowModule();
    BtnToTopModule();
    PopupModule();
    SwiperModule();
    CountUpModule();
    LoadModule();
    SelectCusModule();
    CheckModule();
    SearchModule();
    Select2Module();
    // LetterModule();
    GalleryModule();
    TabModule();
    // IsotopeModule();
    HeaderModule();
    PlusMinusModule();
    SideModule();
    ShowHideModule();
    FaqsModule();
    MapLoadModule();
});